[package]
name = "emissary"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
serde = { version = "1", features = ["derive"] }
awc = "3.0.0-beta.21"
clap = { version = "3", features = ["derive"] }
url = "2.2"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = {version= "0.3"}
uuid = {version = "1.0.0-alpha.1", features = ["v4", "fast-rng", "macro-diagnostics"]}
serde_json = "1.0"
regex = "1.5"