[package]
name = "emissary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
serde = { version = "1", features = ["derive"] }
awc = "3.0.0-beta.21"
clap = { version = "3", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
url = "2.2"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
