name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release
        required: true
        type: string
permissions:
  contents: write
jobs:
  build-linux-x86_64:
    name: Build Linux 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/emissary
  build-apple-x86_64:
    name: Build Apple 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: apple-x86_64
          path: target/x86_64-apple-darwin/release/emissary
  build-apple-arm64:
    name: Build Apple Silicon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
      - uses: actions/upload-artifact@v3
        with:
          name: apple-x86_64
          path: target/aarch64-apple-darwin/release/emissary
#  tag:
#    name: Tag
#    runs-on: ubuntu-latest
#    needs:
#      - build-linux-x86_64
#      - build-apple-x86_64
#      - build-apple-arm64
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Create Tag
#        uses: negz/create-tag@v1
#        with:
#          version: ${{ github.event.inputs.version }}
#          token: ${{ secrets.GITHUB_TOKEN }}
