name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release
        required: true
        type: string
permissions:
  contents: write
jobs:
  build-linux-x86_64:
    name: Build Linux 64-bit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install x86_64 Build Dependencies
        run: sudo apt-get update && sudo apt-get install pkg-config libssl-dev clang
      - name: Build x86_64
        uses: actions-rs/cargo@v1
        env:
          TARGET_CC: clang
        with:
          command: build
          args: --release --target=${{ matrix.target }}
#      - uses: actions/upload-artifact@v3
#        with:
#          name: linux-x86_64
#          path: target/x86_64-unknown-linux-gnu/release/emissary
#  tag:
#    name: Tag
#    runs-on: ubuntu-latest
#    needs:
#      - build-linux-x86_64
#      - build-apple-x86_64
#      - build-apple-arm64
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Create Tag
#        uses: negz/create-tag@v1
#        with:
#          version: ${{ github.event.inputs.version }}
#          token: ${{ secrets.GITHUB_TOKEN }}
